In [1]:
#Initialize the inputs 

import numpy as np
import matplotlib.pyplot as plot

X = np.array(([2, 8],[3, 7],[10, 5]), dtype=float)
y = np.array(([18], [29], [95]), dtype=float)
X = X / np.amax(X, axis=0)
y = y / 100

Initialize the NN. Run forward propagation with random weights

In [2]:
from neural_network import NeuralNetwork 
nn = NeuralNetwork(
        input_layer_size=2,
        hidden_layer_size=3,
        output_layer_size=1)
yHat = nn.forward(X)
yHat

array([[ 0.43000372],
       [ 0.43782683],
       [ 0.49521224]])

In [3]:
nn.weights_1

array([[-1.35298882, -2.58350412, -0.52468069],
       [ 0.10281929,  2.72918547, -0.95628327]])

In [4]:
nn.weights_2

array([[ 0.24301104],
       [-0.53564556],
       [ 0.34868944]])

In [5]:
nn.yHat

array([[ 0.43000372],
       [ 0.43782683],
       [ 0.49521224]])

In [6]:
y

array([[ 0.18],
       [ 0.29],
       [ 0.95]])

In [7]:
nn.eval_function(np.dot(nn.hidden_layer, nn.weights_2))

array([[ 0.43000372],
       [ 0.43782683],
       [ 0.49521224]])

In [8]:
delta3 = np.multiply(-(y-nn.yHat), nn.eval_prime_function(nn.z3))

In [9]:
dJdW2 = np.dot(nn.hidden_layer.T, delta3)
dJdW2

array([[ 0.01885228],
       [ 0.05218798],
       [-0.00233845]])

In [10]:
cost1 = nn.cost(X, y)
cost1

array([ 0.14559327])

In [11]:
scalar = 3.
dJdW1, dJdW2 = nn.cost_function_prime(X,y)
nn.weights_1 = nn.weights_1 - (dJdW1 * scalar )
nn.weights_2 = nn.weights_2 - (dJdW2 * scalar )
cost2 = nn.cost(X,y)

In [12]:
cost1, cost2

(array([ 0.14559327]), array([ 0.13741903]))

Check correctness of numerical gradient computation by using the definition of a derivative

In [13]:
def compute_num_gradient(N, X, y):
    initial_weights = N.get_weights()
    numerical_gradient = np.zeros(initial_weights.shape)
    perturb = np.zeros(initial_weights.shape)
    e = 1e-4
    for p in xrange(len(initial_weights)):
        perturb[p] = e
        N.set_weights(initial_weights + perturb)
        loss1 = N.cost(X, y)
        
        N.set_weights(initial_weights - perturb)
        loss2 = N.cost(X, y)
        
        numerical_gradient[p] = (loss1 - loss2) / (2*e)
        
        perturb[p] = 0

    N.set_weights(initial_weights)
    
    return numerical_gradient

In [14]:
implemented_gradient = nn.compute_gradients(X, y)
computed_gradient = compute_num_gradient(nn, X, y)


In [15]:
implemented_gradient

array([-0.00286857,  0.01508232, -0.00650375,  0.00106517,  0.00492234,
        0.00019254,  0.00875678,  0.03386476, -0.00890727])

In [16]:
computed_gradient

array([-0.00286857,  0.01508232, -0.00650375,  0.00106517,  0.00492234,
        0.00019254,  0.00875678,  0.03386476, -0.00890727])

In [17]:
#check that difference is small
np.linalg.norm(implemented_gradient - computed_gradient) / np.linalg.norm(implemented_gradient + computed_gradient)

5.5996902901600569e-10

In [18]:
nn.train(X, y)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 53
         Function evaluations: 63
         Gradient evaluations: 63
