In [15]:
#Initialize the inputs 

import numpy as np
import matplotlib.pyplot as plot

X = np.array(([2, 8],[3, 7],[10, 5]), dtype=float)
y = np.array(([18], [29], [95]), dtype=float)
X = X / np.amax(X, axis=0)
y = y / 100

Initialize the NN. Run forward propagation with random weights

In [16]:
from neural_network import NeuralNetwork 
nn = NeuralNetwork(
        input_layer_size=2,
        hidden_layer_size=3,
        output_layer_size=1)
yHat = nn.forward(X)
yHat

array([[ 0.41942265],
       [ 0.40098573],
       [ 0.31551426]])

In [17]:
nn.weights_1

array([[-1.36354624,  1.92104696, -0.26011507],
       [ 3.08656757,  0.21594842,  0.616353  ]])

In [18]:
nn.weights_2

array([[ -7.05808470e-04],
       [ -1.44525624e+00],
       [  9.54913029e-01]])

In [19]:
nn.yHat

array([[ 0.41942265],
       [ 0.40098573],
       [ 0.31551426]])

In [20]:
y

array([[ 0.18],
       [ 0.29],
       [ 0.95]])

In [21]:
nn.eval_function(np.dot(nn.hidden_layer, nn.weights_2))

array([[ 0.41942265],
       [ 0.40098573],
       [ 0.31551426]])

In [22]:
delta3 = np.multiply(-(y-nn.yHat), nn.eval_prime_function(nn.z3))

In [23]:
dJdW2 = np.dot(nn.hidden_layer.T, delta3)
dJdW2

array([[-0.00817388],
       [-0.06564273],
       [-0.01927918]])

In [24]:
cost1 = nn.cost(X, y)
cost1

array([ 0.23610659])

In [25]:
scalar = 3.
dJdW1, dJdW2 = nn.cost_function_prime(X,y)
nn.weights_1 = nn.weights_1 - (dJdW1 * scalar )
nn.weights_2 = nn.weights_2 - (dJdW2 * scalar )
cost2 = nn.cost(X,y)

In [26]:
cost1, cost2

(array([ 0.23610659]), array([ 0.22078652]))

Check correctness of numerical gradient computation by using the definition of a derivative

In [41]:
def compute_num_gradient(N, X, y):
    initial_weights = N.get_weights()
    numerical_gradient = np.zeros(initial_weights.shape)
    perturb = np.zeros(initial_weights.shape)
    e = 1e-4
    for p in xrange(len(initial_weights)):
        perturb[p] = e
        N.set_weights(initial_weights + perturb)
        loss1 = N.cost(X, y)
        
        N.set_weights(initial_weights - perturb)
        loss2 = N.cost(X, y)
        
        numerical_gradient[p] = (loss1 - loss2) / (2*e)
        
        perturb[p] = 0

    N.set_weights(initial_weights)
    
    return numerical_gradient

In [43]:
implemented_gradient = nn.compute_gradients(X, y)
computed_gradient = compute_num_gradient(nn, X, y)


In [44]:
implemented_gradient

array([-0.00070231,  0.01001007, -0.02774131, -0.00030685, -0.01845063,
        0.00346742,  0.01608275, -0.04648219, -0.00501051])

In [45]:
computed_gradient

array([-0.00070231,  0.01001007, -0.02774131, -0.00030685, -0.01845063,
        0.00346742,  0.01608275, -0.04648219, -0.00501051])

In [46]:
#check that difference is small
np.linalg.norm(implemented_gradient - computed_gradient) / np.linalg.norm(implemented_gradient + computed_gradient)

9.0001062334594387e-10