In [1]:
#Initialize the inputs 

import numpy as np
import matplotlib.pyplot as plot

X = np.array(([2, 8],[3, 7],[10, 5]), dtype=float)
y = np.array(([18], [29], [95]), dtype=float)
X = X / np.amax(X, axis=0)
y = y / 100

In [2]:
from neural_network import NeuralNetwork 
nn = NeuralNetwork(2, 3, 1)
yHat = nn.forward(X)
yHat

array([[ 0.46281062],
       [ 0.45261723],
       [ 0.381552  ]])

In [3]:
nn.weights_1

array([[ 1.64351019, -0.21965843,  0.19340534],
       [-0.64667779, -1.30581584, -0.95772756]])

In [4]:
nn.weights_2

array([[-1.47791818],
       [ 0.04187854],
       [ 1.6299979 ]])

In [5]:
nn.yHat

array([[ 0.46281062],
       [ 0.45261723],
       [ 0.381552  ]])

In [6]:
y

array([[ 0.18],
       [ 0.29],
       [ 0.95]])

In [7]:
nn.eval_function(np.dot(nn.hidden_layer, nn.weights_2))

array([[ 0.46281062],
       [ 0.45261723],
       [ 0.381552  ]])

In [8]:
delta3 = np.multiply(-(y-nn.yHat), nn.eval_prime_function(nn.z3))

In [9]:
dJdW2 = np.dot(nn.hidden_layer.T, delta3)
dJdW2

array([[-0.05499131],
       [-0.01139556],
       [-0.02095077]])

In [10]:
cost1 = nn.cost(X, y)
cost1

array([ 0.21477967])

In [11]:
scalar = 3.
dJdW1, dJdW2 = nn.cost_function_prime(X,y)
nn.weights_1 = nn.weights_1 - (dJdW1 * scalar )
nn.weights_2 = nn.weights_2 - (dJdW2 * scalar )
cost2 = nn.cost(X,y)

In [12]:
cost1, cost2

(array([ 0.21477967]), array([ 0.1969921]))